# Site settings
title: Michael Faraday Event
description: Nov 3-5 Dordt University
baseurl: "/faraday" # the subpath of your site, e.g. /blog
url: "https://cvisscher.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Michael Faraday Event
user_description: Nov 6-8 2019, Dordt University
user_title: Dordt University
email: channon.visscher@dordt.edu
twitter_username: dordtuniversity

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /faraday
#  - title: Series
#    url: /series
  - title: Tags
    url: /tags
#  - title: About Me
#    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

theme: jekyll-theme-cayman
